name: test maven
on: push
jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: download code
        uses: actions/checkout@v3

  java:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
           distribution: oracle
           java-version: 17

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build project
        run: mvn clean install 
      - run: cp -r threadleak/target . && ls -l
      - name: Build Image
        run: docker build -t java:latest . 
          