name: test maven
on: push
jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: download code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
           distribution: oracle
           java-version: 17

      - name: Build project
        run: mvn clean install